### PR TITLE
Update smartbuffer.ts

### PR DESCRIPTION
**Pull request by xsilen**
just make a pull request to info you, you solution maybe wrong with some edge effect

### CODE REVIEW

**Comment by JoshGlazebrook** [comment]
Can you explain what exactly you're trying to fix. Looking at some of the additions to the code base, you seem to be adding functionality that isn't really wanted/needed with this library. For example changing the write offset, that is all supposed to be hidden behind the scenes and handles by the library itself as the regular Buffer itself lets you write at specific positions.

**Comment by xsilen** [comment]
i really work tired last night, so just modify code to suit with my project. so i ignore code format 

first the write offset shoule able to be controlled by develop, this is what offset mean. 

second the default behaviour is strange ref: https://runkit.com/58d1df06fb3810001377eecf/58ddfd13ebbd28001426a2f3/branches/master

it should be Buffer <01 02 03 04 05> not <01, 02, 03, 04, 05, 00, 00>

**Comment by rebrec** [comment]
Hello, i was about to open an issue for the same behaviour which looks not logical to me.

When you insert an Uint8 (or something else) at a specific offset : 
- i don't think that should Shift other values to the right  right to the offset

Example of the expected behaviour : https://runkit.com/58de54d1472e4400144a5b93/58de54d1472e4400144a5b94

Please let me know if i am misusing your module and should use some other method to accomplish a byte replacement into a buffer.

**Comment by JoshGlazebrook** [comment]
@rebrec The library was primarily for building network packets when it was originally made. So let's say that we a building a login packet, and the second byte we want to be the length of the body of the packet. In this case inserting at an offset is useful. As far as replacing data, you could get the underlying Buffer itself with .toBuffer(), and then write as a specific offset at this time.

Do you have any ideas on how both ideas could be implemented? 

One example is having .writeValue(value, offset) replace data, and .insertValue(value, offset) insert data like what happens now.

**Comment by rebrec** [comment]
@JoshGlazebrook Indeed, having thoses 2 functions would be exactly what i need.
In fact i need it to something similar as your login example except that i build an "extended" login packet from an existing buildLoginPacket() method. I append some extra bytes to the end of the packet and thus, need to "update" the byteLength field which is at the beginning of the packet (it's just an example, i don't use that for a login packet please don't tell me that it's not logical to directly implement this within the buildLoginPacket() method.

I currently made a workaround by converting it to a buffer, then replacing my expected value, then i need rebuild a new SmartBuffer instance using the fromBuffer() method.

But then the writeOffset is not to the expected value so i am not able to naturally append at the end of the packet using some writeValue(value) function call.

Maybe it could be interesting (if there is no side effects) to set the writeOffset to the actual length of the buffer parametter from the fromBuffer() method ?

Another thing which could help find a not too hackish solution in my situation might be to have the same Util method you already provide for reading the buffer (ie : MoveTo(), rewind() etc)

**Comment by JoshGlazebrook** [comment]
You shouldn't have to convert it to a buffer and then rebuild a new smartbuffer with your work around. Since .toBuffer() returns the underlying buffer itself for that particular smartbuffer instance, any changes you make to that buffer will be reflected in the smartbuffer too.

```javascript
const SmartBuffer = require('smart-buffer').SmartBuffer;

const buff = SmartBuffer.fromSize(100);

buff.writeUInt8(1);
buff.writeUInt8(4);
buff.writeUInt8(1);
buff.writeUInt8(2);
buff.writeUInt8(3);

console.log(buff);
buff.toBuffer().writeUInt8(3, 1);
console.log(buff);
```

```
SmartBuffer {
  length: 5,
  encoding: 'utf8',
  writeOffset: 5,
  readOffset: 0,
  buff: <Buffer 01 04 01 02 03 00 00 00 e8 5e 02 03 01 00 00 00 1b 00 00 00 00 00 00 00 5e a3 9f f8 01 00 00 00 00 00 00 00 00 00 00 00 c0 60 02 03 01 00 00 00 04 00 ... > }
SmartBuffer {
  length: 5,
  encoding: 'utf8',
  writeOffset: 5,
  readOffset: 0,
  buff: <Buffer 01 03 01 02 03 00 00 00 e8 5e 02 03 01 00 00 00 1b 00 00 00 00 00 00 00 5e a3 9f f8 01 00 00 00 00 00 00 00 00 00 00 00 c0 60 02 03 01 00 00 00 04 00 ... > }
```

**Comment by rebrec** [comment]
Thanks for the explaination, i didn't realize that it was returning the underlying buffer.

**Comment by JoshGlazebrook** [comment]
And then as far as this:

> But then the writeOffset is not to the expected value so i am not able to naturally append at the end of the packet using some writeValue(value) function call.

I think I can add the setting of the write offset when a buffer is passed in to create a smartbuffer. I think it was left out because the original use case for passing a buffer was to only read from it, not append onto it. So definitely can add this along with .insertValue().

**Comment by rebrec** [comment]
great ! thanks a lot

**Comment by xsilen** [comment]
the real use case is various. insert buffer with special offset should repack into new SmartBuffer
since there are two many node modules, we need to find out package which is suitful.

we just want buffer with automatic offset (just like array index) behave the same as java StreamOutputBuffer and StreamInputBuffer. 

my current use case is that we neeed to write the length of a subBuffer and the subBuffer. but subBuffer is various. after write subBuffer, check the offset then writeInt16BE(length, 2). 

there also need to `import {Buffer} from "buffer"` because we use it in browser

**Comment by JoshGlazebrook** [comment]
@xsilen Right, but couldn't you just write the subbuffer, and then insert the length at offset 2?

**Comment by xsilen** [comment]
fine, it's awesome

**Pull request closed without merging**
